FROM public.ecr.aws/docker/library/python:3.13-slim

LABEL org.opencontainers.image.source=https://github.com/pvital/simple-fastapi-ng
LABEL org.opencontainers.image.description="Simple FastAPI container"
LABEL org.opencontainers.image.licenses=MIT

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the project into the container
ADD . /app
WORKDIR /app

# Creates a non-root user and adds permission to access the /app folder
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# Sync the project into a new environment, using the frozen lockfile
RUN uv sync --frozen --no-cache

EXPOSE 8000

# Run the application
CMD ["/app/.venv/bin/fastapi", "run", "/app/main.py", "--port", "8000", "--host", "0.0.0.0"]
